import os
import json

products = [
"SAHUMERIOS DUENDES ALQUIMISTAS - VAINILLA ENCANTADA", "SAHUMERIOS DUENDES ALQUIMISTAS - MUSK", "SAHUMERIOS DUENDES ALQUIMISTAS - SALVIA BLANCA",
"SAHUMERIOS INDIA HEXAGONAL LINEA BLANCA x 15 - BERRIES", "SAHUMERIOS INDIA HEXAGONAL LINEA BLANCA x 15 - AQUA", "SAHUMERIOS INDIA HEXAGONAL LINEA BLANCA x 15 - LEMONGRASS", "SAHUMERIOS INDIA HEXAGONAL LINEA BLANCA x 15 - MANGO", "SAHUMERIOS INDIA HEXAGONAL LINEA BLANCA x 15 - SANDIA", "SAHUMERIOS INDIA HEXAGONAL x 15 PROMO - CHAMPA", "SAHUMERIOS INDIA HEXAGONAL x 15 PROMO - COCO", "SAHUMERIOS INDIA HEXAGONAL x 15 PROMO - JAZMIN", "SAHUMERIOS INDIA HEXAGONAL x 15 PROMO - LAVANDA", "SAHUMERIOS INDIA HEXAGONAL x 15 PROMO - PATCHOULI", "SAHUMERIOS INDIA HEXAGONAL x 15 PROMO - ROSA", "SAHUMERIOS INDIA HEXAGONAL x 15 PROMO - SANDAL WOOD", "SAHUMERIOS INDIA HEXAGONAL x 15 PROMO - VIOLETAS", "SAHUMERIOS INDIA HEXAGONAL x 15 PROMO - VAINILLA", "SAHUMERIOS INDIA ILUMINARTE POUCH X UNIDAD (NUEVO) - CHAMPA", "SAHUMERIOS INDIA ILUMINARTE POUCH X UNIDAD (NUEVO) - FRUTILLA", "SAHUMERIOS INDIA ILUMINARTE POUCH X UNIDAD (NUEVO) - INCIENSO", "SAHUMERIOS INDIA ILUMINARTE POUCH X UNIDAD (NUEVO) - LAVANDA FRANCESA", "SAHUMERIOS INDIA ILUMINARTE POUCH X UNIDAD (NUEVO) - MIRRA", "SAHUMERIOS INDIA ILUMINARTE POUCH X UNIDAD (NUEVO) - REINA DE LA NOCHE", "SAHUMERIOS INDIA ILUMINARTE POUCH X UNIDAD (NUEVO) - SÁNDALO", "SAHUMERIOS 7 CHAKRAS ( 7 X 3 ) ILUMINARTE -", "SAHUMERIOS BOMBAY TRIPLE EMPASTE x 6 PROMO - 212 PARFUM", "SAHUMERIOS BOMBAY TRIPLE EMPASTE x 6 PROMO - ATRAE DINERO (RIQUEZA)", "SAHUMERIOS BOMBAY TRIPLE EMPASTE x 6 PROMO - ABUNDANCIA (PROSPERIDAD)", "SAHUMERIOS BOMBAY TRIPLE EMPASTE x 6 PROMO - BUENA ONDA (FUERZA POSITIVA)", "SAHUMERIOS BOMBAY TRIPLE EMPASTE x 6 PROMO - FELICIDAD (ALEGRIA Y DICHA)", "SAHUMERIOS BOMBAY TRIPLE EMPASTE x 6 PROMO - LIMPIEZA (QUITA MALA ONDA)", "SAHUMERIOS BOMBAY TRIPLE EMPASTE x 6 PROMO - VARIEDAD", "SAHUMERIOS BOMBAY TRIPLE EMPASTE x 6 PROMO - ENERGÍA LIMPIA", "SAHUMERIOS INDIA ILUMINARTE POUCH X UNIDAD PROMO - VIOLETAS", "SAHUMERIOS INDIA PAQUETE X 15 - BERRIES", "SAHUMERIOS INDIA PAQUETE X 15 - FRUTILLA", "SAHUMERIOS INDIA PAQUETE X 15 - MANGO", "SAHUMERIOS INDIA PAQUETE X 15 - VAINILLA", "SAHUMERIOS INDIA PAQUETE X 15 - SÁNDALO", "SAHUMERIOS INDIA PAQUETE X 15 - ROSA", "SAHUMERIOS INDIA PAQUETE X 15 - PALO SANTO", "SAHUMERIOS INDIA PAQUETE X 15 - LIMÓN", "SAHUMERIOS INDIA PAQUETE X 15 - LAVANDA", "SAHUMERIOS INDIA PAQUETE X 15 - INCIENSO", "SAHUMERIOS INDIA PAQUETE X 15 - ATRAE DINERO", "SAHUMERIOS PALO SANTO BUENA ONDA CAJA X 8 PROMO - FRAGANCIA ORIENTAL", "SAHUMERIOS PALO SANTO BUENA ONDA CAJA X 8 PROMO - DIAMANTE NEGRO", "SAHUMERIOS PALO SANTO BUENA ONDA CAJA X 8 PROMO - FRUTOS ROJOS", "SAHUMERIOS PALO SANTO BUENA ONDA CAJA X 8 PROMO - GARDENIA Y FLORES BLANCAS", "SAHUMERIOS PALO SANTO BUENA ONDA CAJA X 8 PROMO - LA VIDA ES BELLA", "SAHUMERIOS PALO SANTO BUENA ONDA CAJA X 8 PROMO - NARANJA PIMIENTA", "SAHUMERIOS PALO SANTO BUENA ONDA CAJA X 8 PROMO - SANDALO HINDU", "SAHUMERIOS PALO SANTO BUENA ONDA CAJA X 8 PROMO - VARIEDAD", "SAHUMERIOS MINI PALO SANTO BUENA ONDA - COCO VAI", "SAHUMERIOS MINI PALO SANTO BUENA ONDA - YAGRA", "SAHUMERIOS MINI PALO SANTO BUENA ONDA - VARIEDAD", "SAHUMERIOS MINI TIBETANO AROMANZA - REAL ROSE", "SAHUMERIOS MINI TIBETANO AROMANZA - OCEAN BLUE", "SAHUMERIOS MINI TIBETANO AROMANZA - NECTAR DE LOS DIOSES", "SAHUMERIOS MINI TIBETANO AROMANZA - VARIEDAD", "SAHUMERIOS MINI TIBETANO AROMANZA - 7 PODERES", "BOMBITA SAGRADA MADRE DEFUMACION PAQUETE X 4 - ABUNDANCIA INFINITA", "BOMBITA SAGRADA MADRE DEFUMACION PAQUETE X 4 - ATRAE DINERO", "BOMBITA SAGRADA MADRE DEFUMACION PAQUETE X 4 - FUERZA INFINITA", "BOMBITA SAGRADA MADRE DEFUMACION PAQUETE X 4 - DESTRABE", "BOMBITA SAGRADA MADRE DEFUMACION PAQUETE X 4 - LIMPIEZA ENERGÉTICA", "BOMBITA SAGRADA MADRE DEFUMACION PAQUETE X 4 - LIMPIEZA AURICA", "BOMBITA SAGRADA MADRE DEFUMACION PAQUETE X 4 - ABRECAMINO", "SAHUMERIOS SAGRADA MADRE NATURAL PREMIUM SLIM - POMELO", "SAHUMERIOS SAGRADA MADRE NATURAL PREMIUM SLIM - UVA", "SAHUMERIOS SAGRADA MADRE NATURAL PREMIUM SLIM - MELON", "SAHUMERIOS SAGRADA MADRE NATURAL PREMIUM SLIM - SANDIA", "SAHUMERIOS VISHNU HEXAGONAL x 20 - ALMIZCLE", "SAHUMERIOS VISHNU HEXAGONAL x 20 - ANTIESTRES", "SAHUMERIOS VISHNU HEXAGONAL x 20 - FLOR DE LIS", "SAHUMERIOS VISHNU HEXAGONAL x 20 - NAG CHAMPA", "SAHUMERIOS VISHNU HEXAGONAL x 20 - NARANJA - COCO", "SAHUMERIOS VISHNU HEXAGONAL x 20 - MIL FLORES", "SAHUMERIOS VISHNU HEXAGONAL x 20 - MADERA DE ORIENTE", "SAHUMERIOS VISHNU HEXAGONAL x 20 - OM", "SAHUMERIOS VISHNU HEXAGONAL x 20 - PATCHOULI Y NARANJA", "SAHUMERIOS VISHNU HEXAGONAL x 20 - SÁNDALO CANELA", "SAHUMERIOS VISHNU HEXAGONAL x 20 - ROSA BLANCA", "SAHUMERIOS TUK TUK HINDU X 100 VARILLAS PROMO - BUBBLEGUM", "SAHUMERIOS DARSHAN DHOOP - COOL WATER", "SAHUMERIOS DARSHAN POUCH X 15 UNIDADES - AROMAS DE LA INDIA", "SAHUMERIOS DARSHAN POUCH X 15 UNIDADES - FRUTOS TROPICALES", "SAHUMERIOS DARSHAN POUCH X 15 UNIDADES - SALUD, DINERO Y AMOR", "SAHUMERIOS DARSHAN POUCH X 15 UNIDADES - MIL FLORES", "TEXTIL AMBAR 150ml. - UVA", "TEXTIL AMBAR 150ml. - PAPAYA", "TEXTIL AMBAR 150ml. - TROPICAL", "TEXTIL AMBAR 150ml. - LIMÓN", "TEXTIL AMBAR 150ml. - MAGNOLIA Y FRESIAS", "TEXTIL AMBAR 150ml. - HAWAI", "TEXTIL AMBAR 150ml. - COCO VAI", "TEXTIL AMBAR 150ml. - BEBE"
]

images = os.listdir('c:/sahumerios/img')

import re
def normalize(s):
    s = s.lower()
    s = re.sub(r'[^a-z0-9]', ' ', s)
    return set(s.split())

mapping = {}
for p in products:
    p_words = normalize(p)
    best_img = ''
    max_overlap = 0
    for img in images:
        img_words = normalize(img)
        overlap = len(p_words.intersection(img_words))
        if overlap > max_overlap:
            max_overlap = overlap
            best_img = img
    if max_overlap > 0:
        mapping[p] = f'img/{best_img}'

with open('c:/sahumerios/mapping.json', 'w') as f:
    json.dump(mapping, f, indent=2)
